#!/bin/sh
mvn clean package && docker build -t deepk1820/MSAApp2 .
docker rm -f MSAApp2 2>/dev/null || true && docker run -it --name MSAApp2 -p 8080:8080 -p 4848:4848 -p 8181:8181 --name MSAApp2 deepk1820/MSAApp2
